# Generated by Django 3.0.4 on 2020-03-19 14:48

import datalake_rest_apis.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalake_rest_apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdatafile',
            name='file_type',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='rawdatafile',
            name='file',
            field=models.FileField(storage=datalake_rest_apis.storage_backends.StaticStorage(), upload_to=''),
        ),
    ]
