# Generated by Django 3.0.4 on 2020-03-18 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datalake_rest_apis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileItem',
            new_name='RawData',
        ),
    ]
