# Generated by Django 3.0.4 on 2020-03-18 22:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('datalake_rest_apis', '0002_auto_20200318_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawDataFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('path', models.TextField(blank=True, null=True)),
                ('size', models.BigIntegerField(default=0)),
                ('file_type', models.CharField(blank=True, max_length=120, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uploaded', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='RawData',
        ),
    ]
