# Generated by Django 3.0.4 on 2020-03-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalake_rest_apis', '0002_auto_20200319_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdatafile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
