container_commands:
  01_migrate:
    command: "source /opt/python/run/venv/bin/activate && python django_server/manage.py migrate --noinput"
    leader_only: true
  02_createsu:
    command: "source /opt/python/run/venv/bin/activate && python django_server/manage.py createsu"
    leader_only: true
option_settings:
  aws:elasticbeanstalk:application:environment:
    DJANGO_SETTINGS_MODULE: django_server.settings
